# Project: Project1
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Node.o Playlist.o Song.o
LINKOBJ  = main.o Node.o Playlist.o Song.o
LIBS     = -L"D:/App/Dev_C++/Dev-Cpp/TDM-GCC-64/lib" -L"D:/App/Dev_C++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/App/Dev_C++/Dev-Cpp/TDM-GCC-64/include" -I"D:/App/Dev_C++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/App/Dev_C++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/App/Dev_C++/Dev-Cpp/TDM-GCC-64/include" -I"D:/App/Dev_C++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/App/Dev_C++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/App/Dev_C++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "Music Streaming Playlist Manager.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\App\Dev_C++\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Node.o: Node.cpp
	$(CPP) -c Node.cpp -o Node.o $(CXXFLAGS)

Playlist.o: Playlist.cpp
	$(CPP) -c Playlist.cpp -o Playlist.o $(CXXFLAGS)

Song.o: Song.cpp
	$(CPP) -c Song.cpp -o Song.o $(CXXFLAGS)
